blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/yourusername/ai-chess-match/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📚 Documentation
    url: https://github.com/yourusername/ai-chess-match/tree/main/docs
    about: Read the full documentation
  - name: 🚀 Performance Guide
    url: https://github.com/yourusername/ai-chess-match/blob/main/PERFORMANCE_OPTIMIZATION.md
    about: Learn about performance optimization